teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.5
      y: 0.5
    scale_linear_turbo:
      x: 1.0
      y: 1.0

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.75
    scale_angular_turbo:
      yaw: 1.25

    inverted_reverse: False

    enable_button: 10  # R1 shoulder button
    enable_turbo_button: 9  # L1 shoulder button
